import { SelectOption } from "../../components/primitives/types"

export const enum DatabaseTable {
    DONATIONS = "donations",
    DONOR_PROFILES = "donor_profiles",
    EVENTS = "events",
    KINSHIP_CARTS = "kinship_carts",
}

export const countries: SelectOption[] = [
    {"label": "Canada", "value": "ca"}, 
    {"label": "United States", "value": "us"}, 
    {"label": "Afghanistan", "value": "af"}, 
    {"label": "land Islands", "value": "ax"}, 
    {"label": "Albania", "value": "al"}, 
    {"label": "Algeria", "value": "dz"}, 
    {"label": "American Samoa", "value": "as"}, 
    {"label": "Andorra", "value": "ad"}, 
    {"label": "Angola", "value": "ao"}, 
    {"label": "Anguilla", "value": "ai"}, 
    {"label": "Antarctica", "value": "aq"}, 
    {"label": "Antigua and Barbuda", "value": "ag"}, 
    {"label": "Argentina", "value": "ar"}, 
    {"label": "Armenia", "value": "am"}, 
    {"label": "Aruba", "value": "aw"}, 
    {"label": "Australia", "value": "au"}, 
    {"label": "Austria", "value": "at"}, 
    {"label": "Azerbaijan", "value": "az"}, 
    {"label": "Bahamas", "value": "bs"}, 
    {"label": "Bahrain", "value": "bh"}, 
    {"label": "Bangladesh", "value": "bd"}, 
    {"label": "Barbados", "value": "bb"}, 
    {"label": "Belarus", "value": "by"}, 
    {"label": "Belgium", "value": "be"}, 
    {"label": "Belize", "value": "bz"}, 
    {"label": "Benin", "value": "bj"}, 
    {"label": "Bermuda", "value": "bm"}, 
    {"label": "Bhutan", "value": "bt"}, 
    {"label": "Bolivia", "value": "bo"}, 
    {"label": "Bosnia and Herzegovina", "value": "ba"}, 
    {"label": "Botswana", "value": "bw"}, 
    {"label": "Bouvet Island", "value": "bv"}, 
    {"label": "Brazil", "value": "br"}, 
    {"label": "British Indian Ocean Territory", "value": "io"}, 
    {"label": "Brunei Darussalam", "value": "bn"}, 
    {"label": "Bulgaria", "value": "bg"}, 
    {"label": "Burkina Faso", "value": "bf"}, 
    {"label": "Burundi", "value": "bi"}, 
    {"label": "Cambodia", "value": "kh"}, 
    {"label": "Cameroon", "value": "cm"}, 
    {"label": "Cape Verde", "value": "cv"}, 
    {"label": "Cayman Islands", "value": "ky"}, 
    {"label": "Central African Republic", "value": "cf"}, 
    {"label": "Chad", "value": "td"}, 
    {"label": "Chile", "value": "cl"}, 
    {"label": "China", "value": "cn"}, 
    {"label": "Christmas Island", "value": "cx"}, 
    {"label": "Cocos (Keeling) Islands", "value": "cc"}, 
    {"label": "Colombia", "value": "co"}, 
    {"label": "Comoros", "value": "km"}, 
    {"label": "Congo", "value": "cg"}, 
    {"label": "Congo, The Democratic Republic of the", "value": "cd"}, 
    {"label": "Cook Islands", "value": "ck"}, 
    {"label": "Costa Rica", "value": "cr"}, 
    {"label": "Cote D'Ivoire", "value": "ci"}, 
    {"label": "Croatia", "value": "hr"}, 
    {"label": "Cuba", "value": "cu"}, 
    {"label": "Cyprus", "value": "cy"}, 
    {"label": "Czech Republic", "value": "cz"}, 
    {"label": "Denmark", "value": "dk"}, 
    {"label": "Djibouti", "value": "dj"}, 
    {"label": "Dominica", "value": "dm"}, 
    {"label": "Dominican Republic", "value": "do"}, 
    {"label": "Ecuador", "value": "ec"}, 
    {"label": "Egypt", "value": "eg"}, 
    {"label": "El Salvador", "value": "sv"}, 
    {"label": "Equatorial Guinea", "value": "gq"}, 
    {"label": "Eritrea", "value": "er"}, 
    {"label": "Estonia", "value": "ee"}, 
    {"label": "Ethiopia", "value": "et"}, 
    {"label": "Falkland Islands (Malvinas)", "value": "fk"}, 
    {"label": "Faroe Islands", "value": "fo"}, 
    {"label": "Fiji", "value": "fj"}, 
    {"label": "Finland", "value": "fi"}, 
    {"label": "France", "value": "fr"}, 
    {"label": "French Guiana", "value": "gf"}, 
    {"label": "French Polynesia", "value": "pf"}, 
    {"label": "French Southern Territories", "value": "tf"}, 
    {"label": "Gabon", "value": "ga"}, 
    {"label": "Gambia", "value": "gm"}, 
    {"label": "Georgia", "value": "ge"}, 
    {"label": "Germany", "value": "de"}, 
    {"label": "Ghana", "value": "gh"}, 
    {"label": "Gibraltar", "value": "gi"}, 
    {"label": "Greece", "value": "gr"}, 
    {"label": "Greenland", "value": "gl"}, 
    {"label": "Grenada", "value": "gd"}, 
    {"label": "Guadeloupe", "value": "gp"}, 
    {"label": "Guam", "value": "gu"}, 
    {"label": "Guatemala", "value": "gt"}, 
    {"label": "Guernsey", "value": "gg"}, 
    {"label": "Guinea", "value": "gn"}, 
    {"label": "Guinea-Bissau", "value": "gw"}, 
    {"label": "Guyana", "value": "gy"}, 
    {"label": "Haiti", "value": "ht"}, 
    {"label": "Heard Island and Mcdonald Islands", "value": "hm"}, 
    {"label": "Holy See (Vatican City State)", "value": "va"}, 
    {"label": "Honduras", "value": "hn"}, 
    {"label": "Hong Kong", "value": "hk"}, 
    {"label": "Hungary", "value": "hu"}, 
    {"label": "Iceland", "value": "is"}, 
    {"label": "India", "value": "in"}, 
    {"label": "Indonesia", "value": "id"}, 
    {"label": "Iran, Islamic Republic Of", "value": "ir"}, 
    {"label": "Iraq", "value": "iq"}, 
    {"label": "Ireland", "value": "ie"}, 
    {"label": "Isle of Man", "value": "im"}, 
    {"label": "Israel", "value": "il"}, 
    {"label": "Italy", "value": "it"}, 
    {"label": "Jamaica", "value": "jm"}, 
    {"label": "Japan", "value": "jp"}, 
    {"label": "Jersey", "value": "je"}, 
    {"label": "Jordan", "value": "jo"}, 
    {"label": "Kazakhstan", "value": "kz"}, 
    {"label": "Kenya", "value": "ke"}, 
    {"label": "Kiribati", "value": "ki"}, 
    {"label": "Korea, Democratic Peoples Republic of", "value": "kp"}, 
    {"label": "Korea, Republic of", "value": "kr"}, 
    {"label": "Kuwait", "value": "kw"}, 
    {"label": "Kyrgyzstan", "value": "kg"}, 
    {"label": "Lao Peoples Democratic Republic", "value": "la"}, 
    {"label": "Latvia", "value": "lv"}, 
    {"label": "Lebanon", "value": "lb"}, 
    {"label": "Lesotho", "value": "ls"}, 
    {"label": "Liberia", "value": "lr"}, 
    {"label": "Libyan Arab Jamahiriya", "value": "ly"}, 
    {"label": "Liechtenstein", "value": "li"}, 
    {"label": "Lithuania", "value": "lt"}, 
    {"label": "Luxembourg", "value": "lu"}, 
    {"label": "Macao", "value": "mo"}, 
    {"label": "Macedonia, The Former Yugoslav Republic of", "value": "mk"}, 
    {"label": "Madagascar", "value": "mg"}, 
    {"label": "Malawi", "value": "mw"}, 
    {"label": "Malaysia", "value": "my"}, 
    {"label": "Maldives", "value": "mv"}, 
    {"label": "Mali", "value": "ml"}, 
    {"label": "Malta", "value": "mt"}, 
    {"label": "Marshall Islands", "value": "mh"}, 
    {"label": "Martinique", "value": "mq"}, 
    {"label": "Mauritania", "value": "mr"}, 
    {"label": "Mauritius", "value": "mu"}, 
    {"label": "Mayotte", "value": "yt"}, 
    {"label": "Mexico", "value": "mx"}, 
    {"label": "Micronesia, Federated States of", "value": "fm"}, 
    {"label": "Moldova, Republic of", "value": "md"}, 
    {"label": "Monaco", "value": "mc"}, 
    {"label": "Mongolia", "value": "mn"}, 
    {"label": "Montenegro", "value": "me"},
    {"label": "Montserrat", "value": "ms"},
    {"label": "Morocco", "value": "ma"}, 
    {"label": "Mozambique", "value": "mz"}, 
    {"label": "Myanmar", "value": "mm"}, 
    {"label": "Namibia", "value": "na"}, 
    {"label": "Nauru", "value": "nr"}, 
    {"label": "Nepal", "value": "np"}, 
    {"label": "Netherlands", "value": "nl"}, 
    {"label": "Netherlands Antilles", "value": "an"}, 
    {"label": "New Caledonia", "value": "nc"}, 
    {"label": "New Zealand", "value": "nz"}, 
    {"label": "Nicaragua", "value": "ni"}, 
    {"label": "Niger", "value": "ne"}, 
    {"label": "Nigeria", "value": "ng"}, 
    {"label": "Niue", "value": "nu"}, 
    {"label": "Norfolk Island", "value": "nf"}, 
    {"label": "Northern Mariana Islands", "value": "mp"}, 
    {"label": "Norway", "value": "no"}, 
    {"label": "Oman", "value": "om"}, 
    {"label": "Pakistan", "value": "pk"}, 
    {"label": "Palau", "value": "pw"}, 
    {"label": "Palestinian Territory, Occupied", "value": "ps"}, 
    {"label": "Panama", "value": "pa"}, 
    {"label": "Papua New Guinea", "value": "pg"}, 
    {"label": "Paraguay", "value": "py"}, 
    {"label": "Peru", "value": "pe"}, 
    {"label": "Philippines", "value": "ph"}, 
    {"label": "Pitcairn", "value": "pn"}, 
    {"label": "Poland", "value": "pl"}, 
    {"label": "Portugal", "value": "pt"}, 
    {"label": "Puerto Rico", "value": "pr"}, 
    {"label": "Qatar", "value": "qa"}, 
    {"label": "Reunion", "value": "re"}, 
    {"label": "Romania", "value": "ro"}, 
    {"label": "Russian Federation", "value": "ru"}, 
    {"label": "RWANDA", "value": "rw"}, 
    {"label": "Saint Helena", "value": "sh"}, 
    {"label": "Saint Kitts and Nevis", "value": "kn"}, 
    {"label": "Saint Lucia", "value": "lc"}, 
    {"label": "Saint Pierre and Miquelon", "value": "pm"}, 
    {"label": "Saint Vincent and the Grenadines", "value": "vc"}, 
    {"label": "Samoa", "value": "ws"}, 
    {"label": "San Marino", "value": "sm"}, 
    {"label": "Sao Tome and Principe", "value": "st"}, 
    {"label": "Saudi Arabia", "value": "sa"}, 
    {"label": "Senegal", "value": "sn"}, 
    {"label": "Serbia", "value": "rs"}, 
    {"label": "Seychelles", "value": "sc"}, 
    {"label": "Sierra Leone", "value": "sl"}, 
    {"label": "Singapore", "value": "sg"}, 
    {"label": "Slovakia", "value": "sk"}, 
    {"label": "Slovenia", "value": "si"}, 
    {"label": "Solomon Islands", "value": "sb"}, 
    {"label": "Somalia", "value": "so"}, 
    {"label": "South Africa", "value": "za"}, 
    {"label": "South Georgia and the South Sandwich Islands", "value": "gs"}, 
    {"label": "Spain", "value": "es"}, 
    {"label": "Sri Lanka", "value": "lk"}, 
    {"label": "Sudan", "value": "sd"}, 
    {"label": "Suriname", "value": "sr"}, 
    {"label": "Svalbard and Jan Mayen", "value": "sj"}, 
    {"label": "Swaziland", "value": "sz"}, 
    {"label": "Sweden", "value": "se"}, 
    {"label": "Switzerland", "value": "ch"}, 
    {"label": "Syrian Arab Republic", "value": "sy"}, 
    {"label": "Taiwan, Province of China", "value": "tw"}, 
    {"label": "Tajikistan", "value": "tj"}, 
    {"label": "Tanzania, United Republic of", "value": "tz"}, 
    {"label": "Thailand", "value": "th"}, 
    {"label": "Timor-Leste", "value": "tl"}, 
    {"label": "Togo", "value": "tg"}, 
    {"label": "Tokelau", "value": "tk"}, 
    {"label": "Tonga", "value": "to"}, 
    {"label": "Trinidad and Tobago", "value": "tt"}, 
    {"label": "Tunisia", "value": "tn"}, 
    {"label": "Turkey", "value": "tr"}, 
    {"label": "Turkmenistan", "value": "tm"}, 
    {"label": "Turks and Caicos Islands", "value": "tc"}, 
    {"label": "Tuvalu", "value": "tv"}, 
    {"label": "Uganda", "value": "ug"}, 
    {"label": "Ukraine", "value": "ua"}, 
    {"label": "United Arab Emirates", "value": "ae"}, 
    {"label": "United Kingdom", "value": "gb"}, 
    {"label": "United States Minor Outlying Islands", "value": "um"}, 
    {"label": "Uruguay", "value": "uy"}, 
    {"label": "Uzbekistan", "value": "uz"}, 
    {"label": "Vanuatu", "value": "vu"}, 
    {"label": "Venezuela", "value": "ve"}, 
    {"label": "Viet Nam", "value": "vn"}, 
    {"label": "Virgin Islands, British", "value": "vg"}, 
    {"label": "Virgin Islands, U.S.", "value": "vi"}, 
    {"label": "Wallis and Futuna", "value": "wf"}, 
    {"label": "Western Sahara", "value": "eh"}, 
    {"label": "Yemen", "value": "ye"}, 
    {"label": "Zambia", "value": "zm"}, 
    {"label": "Zimbabwe", "value": "zw"} 
]

// This type exists only to make VSCode inferrence and completions easier
type StatesAndProvinces = {
    [key: string]: SelectOption[];
};

export const states_and_provinces: StatesAndProvinces = {
    "ca": [
        { "label": "Ontario", "value": "ON" },
        {
            "label": "Alberta",
            "value": "AB",
        },
        {
            "label": "British Columbia",
            "value": "BC",
        },
        {
            "label": "Manitoba",
            "value": "MB",
        },
        {
            "label": "New Brunswick",
            "value": "NB",
        },
        {
            "label": "Newfoundland and Labrador",
            "value": "CA-NL",
        },
        {
            "label": "Nova Scotia",
            "value": "NS",
        },
        {
            "label": "Prince Edward Island",
            "value": "PE",
        },
        {
            "label": "Quebec",
            "value": "QC",
        },
        {
            "label": "Saskatchewan",
            "value": "SK",
        },
        {
            "label": "Northwest Territories",
            "value": "NT",
        },
        {
            "label": "Nunavut",
            "value": "NU",
        },
        { "label": "Yukon", "value": "YT" }
    ],
    "us": [
        { "label": "Alabama", "value": "AL" },
        { "label": "Alaska", "value": "AK" },
        { "label": "Arizona", "value": "AZ" },
        { "label": "Arkansas", "value": "AR" },
        { "label": "California", "value": "CA" },
        { "label": "Colorado", "value": "CO" },
        { "label": "Connecticut", "value": "CT" },
        { "label": "Delaware", "value": "DE" },
        { "label": "Florida", "value": "FL" },
        { "label": "Georgia", "value": "GA" },
        { "label": "Hawaii", "value": "HI" },
        { "label": "Idaho", "value": "ID" },
        { "label": "Illinois", "value": "IL" },
        { "label": "Indiana", "value": "IN" },
        { "label": "Iowa", "value": "IA" },
        { "label": "Kansas", "value": "KS" },
        { "label": "Kentucky", "value": "KY" },
        { "label": "Louisiana", "value": "LA" },
        { "label": "Maine", "value": "ME" },
        { "label": "Maryland", "value": "MD" },
        { "label": "Massachusetts", "value": "MA" },
        { "label": "Michigan", "value": "MI" },
        { "label": "Minnesota", "value": "MN" },
        { "label": "Mississippi", "value": "MS" },
        { "label": "Missouri", "value": "MO" },
        { "label": "Montana", "value": "MT" },
        { "label": "Nebraska", "value": "NE" },
        { "label": "Nevada", "value": "NV" },
        { "label": "New Hampshire", "value": "NH" },
        { "label": "New Jersey", "value": "NJ" },
        { "label": "New Mexico", "value": "NM" },
        { "label": "New York", "value": "NY" },
        { "label": "North Carolina", "value": "NC" },
        { "label": "North Dakota", "value": "ND" },
        { "label": "Ohio", "value": "OH" },
        { "label": "Oklahoma", "value": "OK" },
        { "label": "Oregon", "value": "OR" },
        { "label": "Pennsylvania", "value": "PA" },
        { "label": "Rhode Island", "value": "RI" },
        { "label": "South Carolina", "value": "SC" },
        { "label": "South Dakota", "value": "SD" },
        { "label": "Tennessee", "value": "TN" },
        { "label": "Texas", "value": "TX" },
        { "label": "Utah", "value": "UT" },
        { "label": "Vermont", "value": "VT" },
        { "label": "Virginia", "value": "VA" },
        { "label": "Washington", "value": "WA" },
        { "label": "West Virginia", "value": "WV" },
        { "label": "Wisconsin", "value": "WI" },
        { "label": "Wyoming", "value": "WY" }
    ]
    
    // Feel free to extend this with your own charitys countries, to make completions easier for donors
}

export const canadian_states = [
	{
		"name": "Alberta",
		"code": "AB",
		"subdivision": "province",
		"native": "Alberta"
	},
	{
		"name": "British Columbia",
		"code": "BC",
		"subdivision": "province",
		"native": "Colombie-Britannique"
	},
	{
		"name": "Manitoba",
		"code": "MB",
		"subdivision": "province",
		"native": "Manitoba"
	},
	{
		"name": "New Brunswick",
		"code": "NB",
		"subdivision": "province",
		"native": "Nouveau-Brunswick"
	},
	{
		"name": "Newfoundland and Labrador",
		"code": "CA-NL",
		"subdivision": "province",
		"native": "Terre-Neuve-et-Labrador"
	},
	{
		"name": "Nova Scotia",
		"code": "NS",
		"subdivision": "province",
		"native": "Nouvelle-Écosse"
	},
	{
		"name": "Ontario",
		"code": "ON",
		"subdivision": "province",
		"native": "Ontario"
	},
	{
		"name": "Prince Edward Island",
		"code": "PE",
		"subdivision": "province",
		"native": "Île-du-Prince-Édouard"
	},
	{
		"name": "Quebec",
		"code": "QC",
		"subdivision": "province",
		"native": "Québec"
	},
	{
		"name": "Saskatchewan",
		"code": "SK",
		"subdivision": "province",
		"native": "Saskatchewan"
	},
	{
		"name": "Northwest Territories",
		"code": "NT",
		"subdivision": "territory",
		"native": "Territoires du Nord-Ouest"
	},
	{
		"name": "Nunavut",
		"code": "NU",
		"subdivision": "territory",
		"native": "Nunavut"
	},
	{
		"name": "Yukon",
		"code": "YT",
		"subdivision": "territory",
		"native": "Yukon"
	}
]

export const causes = [
    {
        cause_id: 0,
        name: "Anywhere",
        description: "I'd like my donation to be allocated wherever it's needed most right now.",
        default_selected: true,
        campaign: false
    },
    {
        cause_id: 8,
        name: 'Vision Kinship',
        description: 'Comprehensively lift a family out of poverty, by helping them start a business, build a home, and provide for their children\'s education.',
        default_selected: false,
        campaign: true
    },
    {
        cause_id: 1,
        name: 'Education',
        description: 'Help the next generation get on their feet. Break the cycle of poverty through education.',
        default_selected: false,
        campaign: false
    },
    {
        cause_id: 2,
        name: 'Orphans',
        description: 'Cover an orphans basic housing, food, educational, and clothing needs.',
        default_selected: false,
        campaign: false
    },
    {
        cause_id: 3,
        name: 'Housing',
        description: 'Provide a roof over the heads of those who need it most. Help them get back on their feet by providing a reliable place to stay.',
        default_selected: false,
        campaign: false
    },
    {
        cause_id: 4,
        name: 'Medical Aid',
        description: 'Contribute to much needed medical aid, including life-saving operations and medication.',
        default_selected: false,
        campaign: false
    },
    {
        cause_id: 5,
        name: 'Poverty Relief',
        description: 'Covers general needs of those in poverty or in extreme situation of needs, such as emergency medical relief, food & water, and more.',
        default_selected: false,
        campaign: false
    },
    {
        cause_id: 6,
        name: 'Khums Donations',
        description: 'Kinship is registered to recieve and distribute Khums donations, also eligible for a tax receipt.',
        default_selected: false,
        campaign: false
    },
]
